name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ruff
      - name: Lint with ruff
        run: |
          export PYVER=$(python -c 'import sys; print("py" + str(sys.version_info.major) + str(sys.version_info.minor))')
          # stop the build if there are Python syntax errors or undefined names
          ruff --config pyproject.toml --select=E9,F63,F7,F82  --target-version=$PYVER .
          # default set of ruff rules with GitHub Annotations
          ruff --config pyproject.toml --target-version=$PYVER .
      # - name: Test with pytest
      #   run: |
      #     pytest
